#ifndef STATUS_H
#define STATUS_H

enum class Status
{
    START_PROGRAM,
    START_LOAD_DATA,
    FINISH_LOAD_DATA,
    OPEN_FILE_ERROR,
    ERROR_APPROXIMATION_OPTIONS,
    APPROXIMATION_START,
    APPROXIMATION_FINISH
};
#endif // STATUS_H
